from _typeshed import Incomplete
from typing import Any

ENCODING: Incomplete


def buffered_hook_manager(header_template: Any, get_pos: Any, cond_refresh: Any, term: Any) -> Any: ...
def passthrough_hook_manager() -> Any: ...
def gen_header(header_template: Any, get_pos: Any) -> Any: ...
def null_header() -> Any: ...
