from .terminal import FULL as FULL
from _typeshed import Incomplete
from typing import Any

PATTERN_SANITIZE: Incomplete
VS_15: str


def print_cells(fragments: Any, cols: Any, last_line_len: int = ..., _term: Any = ...) -> Any: ...
def join_cells(fragment: Any) -> Any: ...
def combine_cells(*fragments: Any) -> Any: ...
def is_wide(g: Any) -> Any: ...
def fix_cells(chars: Any) -> Any: ...
def to_cells(text: Any) -> Any: ...
def split_graphemes(text: Any) -> Any: ...
def mark_graphemes(gs: Any) -> Any: ...
def strip_marks(chars: Any) -> Any: ...
def has_wide(text: Any) -> Any: ...
