from _typeshed import Incomplete
from collections.abc import Generator
from typing import Any


def elapsed_text(seconds: Any, precise: Any) -> Any: ...
def eta_text(eta: Any) -> Any: ...
def simple_eta(logic_total: Any, pos: Any, rate: Any) -> Any: ...
def gen_simple_exponential_smoothing_eta(alfa: Any, logic_total: Any) -> Generator[Incomplete, Incomplete, None]: ...
