from ..utils.cells import combine_cells as combine_cells, fix_cells as fix_cells, mark_graphemes as mark_graphemes, split_graphemes as split_graphemes
from typing import Callable

def spinner_player(spinner): ...
def bordered(borders, default): ...
def extract_fill_graphemes(text, default): ...
def static_sliding_window(sep, gap, contents, length, right, initial): ...
def overlay_sliding_window(background, gap, contents, length, right, initial): ...
def combinations(nums): ...
def split_options(options): ...
def spread_weighted(actual_length, naturals): ...
def fix_signature(func: Callable, source: Callable, skip_n_params: int): ...
def round_even(n): ...
