from collections.abc import Generator
from io import StringIO

class StreamTTY(StringIO):
    def isatty(self): ...

class StreamNonTTY(StringIO):
    def isatty(self): ...

def osname(name) -> Generator[None, None, None]: ...
def replace_by(stream) -> Generator[None, None, None]: ...
def replace_original_by(stream) -> Generator[None, None, None]: ...
def pycharm() -> Generator[None, None, None]: ...
