from ..winterm import WinColor as WinColor, WinStyle as WinStyle, WinTerm as WinTerm
from unittest import TestCase

class WinTermTest(TestCase):
    def testInit(self, mockWin32) -> None: ...
    def testGetAttrs(self) -> None: ...
    def testResetAll(self, mockWin32) -> None: ...
    def testFore(self) -> None: ...
    def testBack(self) -> None: ...
    def testStyle(self) -> None: ...
    def testSetConsole(self, mockWin32) -> None: ...
    def testSetConsoleOnStderr(self, mockWin32) -> None: ...
